### ISSUE TITLE
Alpha biased toward white

### ISSUE THREAD

**Issue by XeroOl** [instantOS/st-instantos#1]
The `-A` flag in `st` should set the alpha. However, when running `st -A 0.0`, the terminal's background is actually tinted white, instead of being transparent. This is not present with vanilla st + alpha patch, so it's possible that some patches are conflicting.

**Comment by XeroOl** [comment]
This issue also occurs if you set `alpha` via XResources.
Reproduce:
1: write `*.alpha=0.0` into ~/.Xresources
2: run `xrdb ~/.Xresources`
3: launch the terminal
4: observe that the terminal isn't entirely transparent, and is still tinted

**Comment by bob8677** [comment]
This seems to be because of the background color, setting `st.background = #000000` in Xresources fixes the problem. 
This is also present in vanilla st when you change the background color, it just happens that vanilla st has a black background.
